-- ============================================================================
-- V001__create_schema.sql
-- Smart Inbox Assistant for a Healthcare Company
-- Core Schema for Oracle Database Free 23ai
-- ============================================================================

-- Switch session to pluggable database FREEPDB1 and target schema SYSTEM
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

-- 1. MESSAGES TABLE
CREATE TABLE IF NOT EXISTS MESSAGES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    source_type VARCHAR2(20 CHAR) DEFAULT 'EMAIL' NOT NULL,
    sender VARCHAR2(255 CHAR),
    subject VARCHAR2(500 CHAR),
    received_date TIMESTAMP,
    body_text CLOB,
    message_id_header VARCHAR2(500 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_msg_source_type CHECK (source_type IN ('EMAIL', 'LITERATURE'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_msg_id_header ON MESSAGES(message_id_header);
CREATE INDEX IF NOT EXISTS idx_messages_received_date ON MESSAGES(received_date);

-- 2. ATTACHMENTS TABLE
CREATE TABLE IF NOT EXISTS ATTACHMENTS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    filename VARCHAR2(255 CHAR) NOT NULL,
    content_type VARCHAR2(100 CHAR),
    is_pdf NUMBER(1,0) DEFAULT 1 NOT NULL,
    storage_path VARCHAR2(1000 CHAR),
    pdf_type VARCHAR2(30 CHAR),
    logged_only NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_attachments_message FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT chk_att_pdf_type CHECK (pdf_type IS NULL OR pdf_type IN ('DIGITAL', 'SCANNED', 'ARTICLE', 'NON_ENGLISH'))
);

CREATE INDEX IF NOT EXISTS idx_attachments_message_id ON ATTACHMENTS(message_id);

-- 3. PDF_SUMMARIES TABLE
CREATE TABLE IF NOT EXISTS PDF_SUMMARIES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    attachment_id NUMBER NOT NULL UNIQUE,
    summary_text CLOB,
    relevance_opinion VARCHAR2(30 CHAR),
    relevance_reason VARCHAR2(1000 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_summaries_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE CASCADE,
    CONSTRAINT chk_sum_rel_opinion CHECK (relevance_opinion IS NULL OR relevance_opinion IN ('RELEVANT', 'NOT_RELEVANT', 'UNCLEAR'))
);

-- 4. PDF_TABLES TABLE
CREATE TABLE IF NOT EXISTS PDF_TABLES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    attachment_id NUMBER NOT NULL,
    page_number NUMBER(5,0),
    table_json CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tables_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pdf_tables_attachment ON PDF_TABLES(attachment_id);

-- 5. PDF_IMAGES TABLE
CREATE TABLE IF NOT EXISTS PDF_IMAGES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    attachment_id NUMBER NOT NULL,
    page_number NUMBER(5,0),
    description VARCHAR2(1000 CHAR),
    review_flag NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_images_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pdf_images_attachment ON PDF_IMAGES(attachment_id);

-- 6. PDF_TRANSLATIONS TABLE
CREATE TABLE IF NOT EXISTS PDF_TRANSLATIONS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    attachment_id NUMBER NOT NULL UNIQUE,
    source_language VARCHAR2(50 CHAR),
    original_text_ref VARCHAR2(500 CHAR),
    translated_text CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_trans_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE CASCADE
);

-- Note: No CREATE INDEX for attachment_id here, as UNIQUE constraint automatically creates and maintains the index.

-- 7. CLASSIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS CLASSIFICATIONS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    category VARCHAR2(50 CHAR) NOT NULL,
    confidence NUMBER(4,3),
    reason VARCHAR2(1000 CHAR),
    reviewer_status VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_classifications_message FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT chk_class_category CHECK (category IN ('SAFETY_REPORT', 'QUALITY_COMPLAINT', 'INFO_REQUEST', 'NOT_RELEVANT')),
    CONSTRAINT chk_class_reviewer_status CHECK (reviewer_status IN ('PENDING', 'ACCEPTED', 'OVERRIDDEN'))
);

CREATE INDEX IF NOT EXISTS idx_class_message_id ON CLASSIFICATIONS(message_id);

-- 8. EXTRACTED_FIELDS TABLE
CREATE TABLE IF NOT EXISTS EXTRACTED_FIELDS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    attachment_id NUMBER,
    field_group VARCHAR2(50 CHAR) NOT NULL,
    field_name VARCHAR2(100 CHAR) NOT NULL,
    field_value CLOB,
    confidence NUMBER(4,3),
    source_type VARCHAR2(30 CHAR),
    source_ref VARCHAR2(255 CHAR),
    reviewer_edited NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_fields_message FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT fk_fields_attachment FOREIGN KEY (attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE SET NULL,
    CONSTRAINT chk_fields_source_type CHECK (source_type IS NULL OR source_type IN ('EMAIL', 'PDF_PAGE'))
);

CREATE INDEX IF NOT EXISTS idx_fields_message_id ON EXTRACTED_FIELDS(message_id);
CREATE INDEX IF NOT EXISTS idx_fields_attachment_id ON EXTRACTED_FIELDS(attachment_id);
CREATE INDEX IF NOT EXISTS idx_fields_group ON EXTRACTED_FIELDS(field_group);

-- 9. REVIEW_ACTIONS TABLE
CREATE TABLE IF NOT EXISTS REVIEW_ACTIONS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    reviewer_name VARCHAR2(100 CHAR) NOT NULL,
    action VARCHAR2(30 CHAR) NOT NULL,
    target_ref VARCHAR2(255 CHAR),
    previous_value CLOB,
    new_value CLOB,
    timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_review_actions_msg FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT chk_review_action CHECK (action IN ('ACCEPT', 'OVERRIDE', 'EDIT'))
);

CREATE INDEX IF NOT EXISTS idx_review_actions_msg_id ON REVIEW_ACTIONS(message_id);

-- 10. AUDIT_LOG TABLE
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR2(50 CHAR) NOT NULL,
    entity_id NUMBER NOT NULL,
    action VARCHAR2(50 CHAR) NOT NULL,
    actor VARCHAR2(20 CHAR) NOT NULL,
    details_json CLOB,
    timestamp TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_audit_actor CHECK (actor IN ('AI', 'REVIEWER'))
);

CREATE INDEX IF NOT EXISTS idx_audit_entity ON AUDIT_LOG(entity_type, entity_id);

-- 11. PROCESSING_JOBS TABLE
CREATE TABLE IF NOT EXISTS PROCESSING_JOBS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_id NUMBER NOT NULL,
    batch_id VARCHAR2(100 CHAR),
    status VARCHAR2(30 CHAR) DEFAULT 'QUEUED' NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    duration_ms NUMBER(19,0),
    error_message VARCHAR2(2000 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_jobs_message FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT chk_job_status CHECK (status IN ('QUEUED', 'PROCESSING', 'DONE', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON PROCESSING_JOBS(status, created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_batch_id ON PROCESSING_JOBS(batch_id);
