-- ============================================================================
-- V002__create_literature_tables.sql
-- Smart Inbox Assistant for a Healthcare Company
-- Bonus Extension: Literature Screening Schema for Oracle 23ai
-- ============================================================================

-- Switch session to pluggable database FREEPDB1 and target schema SYSTEM
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

-- 12. LITERATURE_CASES TABLE (Bonus FR-32 to FR-36)
CREATE TABLE IF NOT EXISTS LITERATURE_CASES (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR2(100 CHAR) NOT NULL,
    message_id NUMBER NOT NULL,
    source_attachment_id NUMBER NOT NULL,
    case_index NUMBER(5,0) DEFAULT 1 NOT NULL,
    is_reportable NUMBER(1,0) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_lit_cases_message FOREIGN KEY (message_id) REFERENCES MESSAGES(id) ON DELETE CASCADE,
    CONSTRAINT fk_lit_cases_attachment FOREIGN KEY (source_attachment_id) REFERENCES ATTACHMENTS(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lit_cases_batch_id ON LITERATURE_CASES(batch_id);
CREATE INDEX IF NOT EXISTS idx_lit_cases_message_id ON LITERATURE_CASES(message_id);
CREATE INDEX IF NOT EXISTS idx_lit_cases_attachment_id ON LITERATURE_CASES(source_attachment_id);
